name: TEST Kics Scan 2

on:
    push:
    
jobs:
    scan:
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            # Scan Iac with kics
            - name: run kics Scan
              uses: checkmarx/kics-github-action@v1.7.0 
              with:
                  # scanning a single file
                  path: 'Dockerfile'
                  ignore_on_exit: results
                  output_path: myResults/
          # Display the results in json format
            - name: display kics results
              run: |
                cat myResults/results.json
