name: Kics scan and SARIF upload

on:
  push:
  pull_request:
  
jobs:
  kics-job:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
      contents: read
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0 
        with:
          path: 'gradle,src,Dockerfile,gradlew'
          output_path: results-dir
          output_formats: 'json,sarif'
      - name: Show results
        run: |
          cat results-dir/results.sarif
          cat results-dir/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif
