name: TEST Kics Scan

on:
    pull_request:
    
jobs:
    scan:
        runs-on: self-hosted
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            # Scan Iac with kics
            - name: run kics Scan
              uses: checkmarx/kics-github-action@v1.7.0 
              with:
                  # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
                  path: 'terraform,cfn-templates,my-other-sub-folder/Dockerfile'
                  output_path: myResults/
          # Display the results in json format
            - name: display kics results
              run: |
                cat myResults/results.json
